modLoader="javafml"
loaderVersion="[43,)"
license="MIT"
issueTrackerURL="https://github.com/TeamTotemic/Totemic/issues"

[[mods]]
modId="totemic"
version="${file.jarVersion}"
displayName="Totemic"
updateJSONURL="https://raw.githubusercontent.com/TeamTotemic/Totemic/version/version.json"
displayURL="https://minecraft.curseforge.com/projects/totemic"
logoFile="totemic_logo.png"
credits="nojustgavin, Nefilto, ZestyBlaze, VincentLongiug, WayofTime, Joshie, Poppycocks, Dylan4Ever, Vazkii, Kerri Lake"
authors="Pokefenn, ljfa, Sunconure11"
description='''
A magic mod about Totem Poles, nature and the power of music.
'''

[[dependencies.totemic]]
    modId="forge"
    mandatory=true
    versionRange="[43.1.7,)"
    ordering="NONE"
    side="BOTH"

[[dependencies.totemic]]
    modId="minecraft"
    mandatory=true
    versionRange="[1.19.2,)"
    ordering="NONE"
    side="BOTH"
